//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.Guid BookingID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid TableID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Table Table { get; set; }
    }
}
