//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public int CartDetailID { get; set; }
        public int OrderCartID { get; set; }
        public System.Guid MenuID { get; set; }
        public System.Guid TableID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual OrderCart OrderCart { get; set; }
        public virtual Table Table { get; set; }
    }
}
